import "./globals.css";
import { type Metadata } from "next";
import { Mona_Sans } from "next/font/google";

const fontSans = Mona_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Formbuilder",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${fontSans.variable} antialiased scheme-dark`}>
      <body>{children}</body>
    </html>
  );
}
